<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
     try {
        \DB::beginTransaction();

        \DB::table('data_rows')->delete();

        \DB::table('data_rows')->insert(array (
                0 => 
                array (
                    'id' => 1,
                    'data_type_id' => 1,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'ID',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 1,
                ),
                1 => 
                array (
                    'id' => 2,
                    'data_type_id' => 1,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Имя',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 2,
                ),
                2 => 
                array (
                    'id' => 3,
                    'data_type_id' => 1,
                    'field' => 'email',
                    'type' => 'text',
                    'display_name' => 'Email',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 3,
                ),
                3 => 
                array (
                    'id' => 4,
                    'data_type_id' => 1,
                    'field' => 'password',
                    'type' => 'password',
                    'display_name' => 'Пароль',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 4,
                ),
                4 => 
                array (
                    'id' => 5,
                    'data_type_id' => 1,
                    'field' => 'remember_token',
                    'type' => 'text',
                    'display_name' => 'Токен восстановления',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 5,
                ),
                5 => 
                array (
                    'id' => 6,
                    'data_type_id' => 1,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата создания',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 6,
                ),
                6 => 
                array (
                    'id' => 7,
                    'data_type_id' => 1,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата обновления',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 7,
                ),
                7 => 
                array (
                    'id' => 8,
                    'data_type_id' => 1,
                    'field' => 'avatar',
                    'type' => 'image',
                    'display_name' => 'Аватар',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 8,
                ),
                8 => 
                array (
                    'id' => 9,
                    'data_type_id' => 1,
                    'field' => 'user_belongsto_role_relationship',
                    'type' => 'relationship',
                    'display_name' => 'Роль',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 0,
                    'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                    'order' => 10,
                ),
                9 => 
                array (
                    'id' => 10,
                    'data_type_id' => 1,
                    'field' => 'user_belongstomany_role_relationship',
                    'type' => 'relationship',
                    'display_name' => 'Roles',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 0,
                    'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                    'order' => 11,
                ),
                10 => 
                array (
                    'id' => 11,
                    'data_type_id' => 1,
                    'field' => 'settings',
                    'type' => 'hidden',
                    'display_name' => 'Settings',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 12,
                ),
                11 => 
                array (
                    'id' => 12,
                    'data_type_id' => 2,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'ID',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 1,
                ),
                12 => 
                array (
                    'id' => 13,
                    'data_type_id' => 2,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Имя',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 2,
                ),
                13 => 
                array (
                    'id' => 14,
                    'data_type_id' => 2,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата создания',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 3,
                ),
                14 => 
                array (
                    'id' => 15,
                    'data_type_id' => 2,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата обновления',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 4,
                ),
                15 => 
                array (
                    'id' => 16,
                    'data_type_id' => 3,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'ID',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 1,
                ),
                16 => 
                array (
                    'id' => 17,
                    'data_type_id' => 3,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Имя',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 2,
                ),
                17 => 
                array (
                    'id' => 18,
                    'data_type_id' => 3,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата создания',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 3,
                ),
                18 => 
                array (
                    'id' => 19,
                    'data_type_id' => 3,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата обновления',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 4,
                ),
                19 => 
                array (
                    'id' => 20,
                    'data_type_id' => 3,
                    'field' => 'display_name',
                    'type' => 'text',
                    'display_name' => 'Отображаемое имя',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 5,
                ),
                20 => 
                array (
                    'id' => 21,
                    'data_type_id' => 1,
                    'field' => 'role_id',
                    'type' => 'text',
                    'display_name' => 'Роль',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 9,
                ),
                21 => 
                array (
                    'id' => 30,
                    'data_type_id' => 5,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => '№',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"1"}}',
                    'order' => 1,
                ),
                22 => 
                array (
                    'id' => 31,
                    'data_type_id' => 5,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Название',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":"2"}}',
                    'order' => 2,
                ),
                23 => 
                array (
                    'id' => 32,
                    'data_type_id' => 5,
                    'field' => 'image',
                    'type' => 'image',
                    'display_name' => 'Изображение',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":"3"},"description":"\\u041e\\u0441\\u043d\\u043e\\u0432\\u043d\\u043e\\u0435 \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435 \\u043a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0438\\u0438"}',
                    'order' => 3,
                ),
                24 => 
                array (
                    'id' => 33,
                    'data_type_id' => 5,
                    'field' => 'deleted_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата удаления',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"2"}}',
                    'order' => 5,
                ),
                25 => 
                array (
                    'id' => 34,
                    'data_type_id' => 5,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата создания',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"2"}}',
                    'order' => 6,
                ),
                26 => 
                array (
                    'id' => 35,
                    'data_type_id' => 5,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Дата обновления',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"2"}}',
                    'order' => 7,
                ),
                27 => 
                array (
                    'id' => 37,
                    'data_type_id' => 6,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'Номер',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"1"}}',
                    'order' => 1,
                ),
                28 => 
                array (
                    'id' => 38,
                    'data_type_id' => 6,
                    'field' => 'category_id',
                    'type' => 'text',
                    'display_name' => '№ Категории',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{"display":{"width":"2"}}',
                    'order' => 12,
                ),
                29 => 
                array (
                    'id' => 39,
                    'data_type_id' => 6,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Модель',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{"display":{"width":"3"}}',
                    'order' => 3,
                ),
                30 => 
                array (
                    'id' => 40,
                    'data_type_id' => 6,
                    'field' => 'image',
                    'type' => 'image',
                    'display_name' => 'Изображение(нужно удалить и добавить галерею в "Галерею изображений"',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 0,
                        'delete' => 1,
                        'details' => '{"display":{"width":"12"},"description":"\\u0415\\u0441\\u043b\\u0438 \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435 \\u0431\\u0443\\u0434\\u0435\\u0442 \\u043e\\u0434\\u043d\\u043e, \\u0442\\u043e\\u0433\\u0434\\u0430 \\u0434\\u043e\\u0431\\u0430\\u0432\\u0438\\u0442\\u044c \\u0432 \\u0434\\u0430\\u043d\\u043d\\u043e\\u0435 \\u043f\\u043e\\u043b\\u0435"}',
                        'order' => 10,
                    ),
                    31 => 
                    array (
                        'id' => 46,
                        'data_type_id' => 6,
                        'field' => 'product_belongsto_category_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Категории',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"},"model":"App\\\\Models\\\\Category","table":"categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 2,
                    ),
                    32 => 
                    array (
                        'id' => 47,
                        'data_type_id' => 7,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    33 => 
                    array (
                        'id' => 48,
                        'data_type_id' => 7,
                        'field' => 'name',
                        'type' => 'text',
                        'display_name' => 'Материал',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"}}',
                        'order' => 2,
                    ),
                    34 => 
                    array (
                        'id' => 49,
                        'data_type_id' => 7,
                        'field' => 'image',
                        'type' => 'image',
                        'display_name' => 'Изображение',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"}}',
                        'order' => 3,
                    ),
                    35 => 
                    array (
                        'id' => 51,
                        'data_type_id' => 7,
                        'field' => 'price',
                        'type' => 'number',
                        'display_name' => 'Стоимость руб/м³',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"description":"\\u0422\\u043e\\u043b\\u044c\\u043a\\u043e \\u0447\\u0438\\u0441\\u043b\\u043e\\u0432\\u043e\\u0435 \\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435, \\u043d\\u0430\\u043f\\u0440\\u0438\\u043c\\u0435\\u0440, 125,00"}',
                        'order' => 5,
                    ),
                    36 => 
                    array (
                        'id' => 58,
                        'data_type_id' => 7,
                        'field' => 'color',
                        'type' => 'text',
                        'display_name' => 'Цвет',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 5,
                    ),
                    37 => 
                    array (
                        'id' => 62,
                        'data_type_id' => 7,
                        'field' => 'country',
                        'type' => 'text',
                        'display_name' => 'Страна',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 6,
                    ),
                    38 => 
                    array (
                        'id' => 63,
                        'data_type_id' => 7,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 7,
                    ),
                    39 => 
                    array (
                        'id' => 64,
                        'data_type_id' => 7,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 8,
                    ),
                    40 => 
                    array (
                        'id' => 67,
                        'data_type_id' => 6,
                        'field' => 'stella_id',
                        'type' => 'text',
                        'display_name' => 'Стелла',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 14,
                    ),
                    41 => 
                    array (
                        'id' => 69,
                        'data_type_id' => 6,
                        'field' => 'tombstone_id',
                        'type' => 'text',
                        'display_name' => 'Надгробная плита',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 17,
                    ),
                    42 => 
                    array (
                        'id' => 70,
                        'data_type_id' => 6,
                        'field' => 'pedestal_id',
                        'type' => 'text',
                    'display_name' => 'Тумба (подставка под стеллу)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 15,
                    ),
                    43 => 
                    array (
                        'id' => 71,
                        'data_type_id' => 6,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 18,
                    ),
                    44 => 
                    array (
                        'id' => 72,
                        'data_type_id' => 6,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 19,
                    ),
                    45 => 
                    array (
                        'id' => 73,
                        'data_type_id' => 8,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    46 => 
                    array (
                        'id' => 81,
                        'data_type_id' => 8,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 10,
                    ),
                    47 => 
                    array (
                        'id' => 82,
                        'data_type_id' => 8,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 11,
                    ),
                    48 => 
                    array (
                        'id' => 85,
                        'data_type_id' => 8,
                        'field' => 'height',
                        'type' => 'number',
                    'display_name' => 'Высота (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 7,
                    ),
                    49 => 
                    array (
                        'id' => 86,
                        'data_type_id' => 8,
                        'field' => 'depth',
                        'type' => 'number',
                    'display_name' => 'Толщина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 8,
                    ),
                    50 => 
                    array (
                        'id' => 88,
                        'data_type_id' => 6,
                        'field' => 'product_belongsto_parterre_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Цветник',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"6"},"model":"App\\\\Models\\\\Parterre","table":"parterres","type":"belongsTo","column":"parterre_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 7,
                    ),
                    51 => 
                    array (
                        'id' => 89,
                        'data_type_id' => 6,
                        'field' => 'parterre_id',
                        'type' => 'text',
                        'display_name' => 'Цветник',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 16,
                    ),
                    52 => 
                    array (
                        'id' => 90,
                        'data_type_id' => 9,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    53 => 
                    array (
                        'id' => 93,
                        'data_type_id' => 9,
                        'field' => 'height',
                        'type' => 'number',
                    'display_name' => 'Высота (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 3,
                    ),
                    54 => 
                    array (
                        'id' => 94,
                        'data_type_id' => 9,
                        'field' => 'width',
                        'type' => 'number',
                    'display_name' => 'Ширина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 4,
                    ),
                    55 => 
                    array (
                        'id' => 95,
                        'data_type_id' => 9,
                        'field' => 'depth',
                        'type' => 'number',
                    'display_name' => 'Толщина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 5,
                    ),
                    56 => 
                    array (
                        'id' => 97,
                        'data_type_id' => 9,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 8,
                    ),
                    57 => 
                    array (
                        'id' => 98,
                        'data_type_id' => 9,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 9,
                    ),
                    58 => 
                    array (
                        'id' => 101,
                        'data_type_id' => 10,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => 'Id',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    59 => 
                    array (
                        'id' => 102,
                        'data_type_id' => 10,
                        'field' => 'name',
                        'type' => 'text',
                        'display_name' => 'Наименование',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"}}',
                        'order' => 2,
                    ),
                    60 => 
                    array (
                        'id' => 103,
                        'data_type_id' => 10,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Стоимость (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 3,
                    ),
                    61 => 
                    array (
                        'id' => 104,
                        'data_type_id' => 10,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 4,
                    ),
                    62 => 
                    array (
                        'id' => 105,
                        'data_type_id' => 10,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 5,
                    ),
                    63 => 
                    array (
                        'id' => 110,
                        'data_type_id' => 6,
                        'field' => 'product_belongsto_stella_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Стелла',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"6"},"model":"App\\\\Models\\\\Stella","table":"stellas","type":"belongsTo","column":"stella_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 5,
                    ),
                    64 => 
                    array (
                        'id' => 112,
                        'data_type_id' => 12,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    65 => 
                    array (
                        'id' => 114,
                        'data_type_id' => 12,
                        'field' => 'height',
                        'type' => 'number',
                    'display_name' => 'Высота (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 5,
                    ),
                    66 => 
                    array (
                        'id' => 115,
                        'data_type_id' => 12,
                        'field' => 'width',
                        'type' => 'number',
                    'display_name' => 'Ширина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 4,
                    ),
                    67 => 
                    array (
                        'id' => 116,
                        'data_type_id' => 12,
                        'field' => 'depth',
                        'type' => 'number',
                    'display_name' => 'Толщина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 6,
                    ),
                    68 => 
                    array (
                        'id' => 117,
                        'data_type_id' => 12,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 8,
                    ),
                    69 => 
                    array (
                        'id' => 118,
                        'data_type_id' => 12,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 9,
                    ),
                    70 => 
                    array (
                        'id' => 119,
                        'data_type_id' => 6,
                        'field' => 'product_belongsto_pedestal_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Тумба',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"6"},"model":"App\\\\Models\\\\Pedestal","table":"pedestals","type":"belongsTo","column":"pedestal_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 6,
                    ),
                    71 => 
                    array (
                        'id' => 122,
                        'data_type_id' => 6,
                        'field' => 'product_belongsto_tombstone_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Надгробная плита',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"6"},"model":"App\\\\Models\\\\Tombstone","table":"tombstones","type":"belongsTo","column":"tombstone_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 8,
                    ),
                    72 => 
                    array (
                        'id' => 123,
                        'data_type_id' => 13,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    73 => 
                    array (
                        'id' => 124,
                        'data_type_id' => 13,
                        'field' => 'height',
                        'type' => 'number',
                    'display_name' => 'Высота (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 4,
                    ),
                    74 => 
                    array (
                        'id' => 125,
                        'data_type_id' => 13,
                        'field' => 'width',
                        'type' => 'number',
                    'display_name' => 'Ширина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 5,
                    ),
                    75 => 
                    array (
                        'id' => 126,
                        'data_type_id' => 13,
                        'field' => 'depth',
                        'type' => 'number',
                    'display_name' => 'Толщина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 6,
                    ),
                    76 => 
                    array (
                        'id' => 127,
                        'data_type_id' => 13,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 8,
                    ),
                    77 => 
                    array (
                        'id' => 128,
                        'data_type_id' => 13,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 9,
                    ),
                    78 => 
                    array (
                        'id' => 129,
                        'data_type_id' => 9,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Цена (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 7,
                    ),
                    79 => 
                    array (
                        'id' => 130,
                        'data_type_id' => 9,
                        'field' => 'material_id',
                        'type' => 'text',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"}}',
                        'order' => 6,
                    ),
                    80 => 
                    array (
                        'id' => 131,
                        'data_type_id' => 9,
                        'field' => 'stella_belongsto_material_relationship',
                        'type' => 'relationship',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"},"model":"App\\\\Models\\\\Material","table":"materials","type":"belongsTo","column":"material_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 2,
                    ),
                    81 => 
                    array (
                        'id' => 132,
                        'data_type_id' => 12,
                        'field' => 'pedestal_belongsto_material_relationship',
                        'type' => 'relationship',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"},"model":"App\\\\Models\\\\Material","table":"materials","type":"belongsTo","column":"material_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 2,
                    ),
                    82 => 
                    array (
                        'id' => 133,
                        'data_type_id' => 12,
                        'field' => 'material_id',
                        'type' => 'text',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 3,
                    ),
                    83 => 
                    array (
                        'id' => 134,
                        'data_type_id' => 12,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Цена (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 7,
                    ),
                    84 => 
                    array (
                        'id' => 135,
                        'data_type_id' => 8,
                        'field' => 'parterre_belongsto_material_relationship',
                        'type' => 'relationship',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"},"model":"App\\\\Models\\\\Material","table":"materials","type":"belongsTo","column":"material_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 2,
                    ),
                    85 => 
                    array (
                        'id' => 136,
                        'data_type_id' => 8,
                        'field' => 'material_id',
                        'type' => 'text',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"}}',
                        'order' => 3,
                    ),
                    86 => 
                    array (
                        'id' => 137,
                        'data_type_id' => 8,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Цена (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 9,
                    ),
                    87 => 
                    array (
                        'id' => 138,
                        'data_type_id' => 13,
                        'field' => 'tombstone_belongsto_material_relationship',
                        'type' => 'relationship',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"},"model":"App\\\\Models\\\\Material","table":"materials","type":"belongsTo","column":"material_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 2,
                    ),
                    88 => 
                    array (
                        'id' => 139,
                        'data_type_id' => 13,
                        'field' => 'material_id',
                        'type' => 'text',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 3,
                    ),
                    89 => 
                    array (
                        'id' => 140,
                        'data_type_id' => 13,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Цена (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 7,
                    ),
                    90 => 
                    array (
                        'id' => 141,
                        'data_type_id' => 6,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Цена (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"}}',
                        'order' => 4,
                    ),
                    91 => 
                    array (
                        'id' => 142,
                        'data_type_id' => 17,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    92 => 
                    array (
                        'id' => 143,
                        'data_type_id' => 17,
                        'field' => 'material_id',
                        'type' => 'text',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"}}',
                        'order' => 6,
                    ),
                    93 => 
                    array (
                        'id' => 144,
                        'data_type_id' => 17,
                        'field' => 'height',
                        'type' => 'number',
                    'display_name' => 'Высота (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 3,
                    ),
                    94 => 
                    array (
                        'id' => 145,
                        'data_type_id' => 17,
                        'field' => 'width',
                        'type' => 'number',
                    'display_name' => 'Ширина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 4,
                    ),
                    95 => 
                    array (
                        'id' => 146,
                        'data_type_id' => 17,
                        'field' => 'depth',
                        'type' => 'number',
                    'display_name' => 'Толщина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 5,
                    ),
                    96 => 
                    array (
                        'id' => 147,
                        'data_type_id' => 17,
                        'field' => 'price',
                        'type' => 'number',
                    'display_name' => 'Цена (руб)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 7,
                    ),
                    97 => 
                    array (
                        'id' => 148,
                        'data_type_id' => 17,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания записи',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 8,
                    ),
                    98 => 
                    array (
                        'id' => 149,
                        'data_type_id' => 17,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления записи',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 9,
                    ),
                    99 => 
                    array (
                        'id' => 150,
                        'data_type_id' => 17,
                        'field' => 'pillar_belongsto_material_relationship',
                        'type' => 'relationship',
                    'display_name' => 'Материал (камень)',
                        'required' => 1,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"},"model":"App\\\\Models\\\\Material","table":"materials","type":"belongsTo","column":"material_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 2,
                    ),
                    100 => 
                    array (
                        'id' => 151,
                        'data_type_id' => 6,
                        'field' => 'product_belongsto_pillar_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Столбик',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"6"},"model":"App\\\\Models\\\\Pillar","table":"pillars","type":"belongsTo","column":"pillar_id","key":"id","label":"full_data","pivot_table":"categories","pivot":"0","taggable":"0"}',
                        'order' => 9,
                    ),
                    101 => 
                    array (
                        'id' => 152,
                        'data_type_id' => 6,
                        'field' => 'pillar_id',
                        'type' => 'text',
                        'display_name' => 'Столбик',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 13,
                    ),
                    102 => 
                    array (
                        'id' => 153,
                        'data_type_id' => 8,
                        'field' => 'length',
                        'type' => 'number',
                    'display_name' => 'Длина (сантиметр)',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"default":"0"}',
                        'order' => 4,
                    ),
                    103 => 
                    array (
                        'id' => 154,
                        'data_type_id' => 6,
                        'field' => 'images',
                        'type' => 'multiple_images',
                        'display_name' => 'Галерея изображений',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"12"},"description":"\\u0415\\u0441\\u043b\\u0438 \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0439 \\u0431\\u0443\\u0434\\u0435\\u0442 \\u043c\\u043d\\u043e\\u0433\\u043e, \\u0442\\u043e\\u0433\\u0434\\u0430 \\u0434\\u043e\\u0431\\u0430\\u0432\\u0438\\u0442\\u044c \\u0432 \\u0434\\u0430\\u043d\\u043d\\u043e\\u0435 \\u043f\\u043e\\u043b\\u0435"}',
                        'order' => 11,
                    ),
                    104 => 
                    array (
                        'id' => 158,
                        'data_type_id' => 5,
                        'field' => 'category_hasone_product_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Памятники',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 0,
                        'delete' => 1,
                        'details' => '{"display":{"width":"3"},"model":"App\\\\Models\\\\Product","table":"products","type":"hasMany","column":"category_id","key":"id","label":"name","pivot_table":"accessories","pivot":"0","taggable":"0"}',
                        'order' => 4,
                    ),
                    105 => 
                    array (
                        'id' => 159,
                        'data_type_id' => 18,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    106 => 
                    array (
                        'id' => 160,
                        'data_type_id' => 18,
                        'field' => 'name',
                        'type' => 'text',
                        'display_name' => 'Наименование',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"}}',
                        'order' => 2,
                    ),
                    107 => 
                    array (
                        'id' => 161,
                        'data_type_id' => 18,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 4,
                    ),
                    108 => 
                    array (
                        'id' => 162,
                        'data_type_id' => 18,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 5,
                    ),
                    109 => 
                    array (
                        'id' => 163,
                        'data_type_id' => 18,
                        'field' => 'image',
                        'type' => 'image',
                        'display_name' => 'Изображение каталога',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"}}',
                        'order' => 3,
                    ),
                    110 => 
                    array (
                        'id' => 193,
                        'data_type_id' => 22,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    111 => 
                    array (
                        'id' => 194,
                        'data_type_id' => 22,
                        'field' => 'name',
                        'type' => 'text',
                        'display_name' => 'Наименование',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"}}',
                        'order' => 2,
                    ),
                    112 => 
                    array (
                        'id' => 195,
                        'data_type_id' => 22,
                        'field' => 'description',
                        'type' => 'rich_text_box',
                        'display_name' => 'Описание',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"12"},"description":"\\u041a\\u0440\\u0430\\u0442\\u043a\\u043e\\u0435 \\u043e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435 \\u0442\\u043e\\u0432\\u0430\\u0440\\u0430. \\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u043d\\u043e \\u0444\\u043e\\u0440\\u043c\\u0430\\u0442\\u0438\\u0440\\u043e\\u0432\\u0430\\u043d\\u0438\\u0435 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430"}',
                        'order' => 4,
                    ),
                    113 => 
                    array (
                        'id' => 196,
                        'data_type_id' => 22,
                        'field' => 'image',
                        'type' => 'image',
                        'display_name' => 'Изображение',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"description":"\\u0415\\u0441\\u043b\\u0438 \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435 \\u0431\\u0443\\u0434\\u0435\\u0442 \\u043e\\u0434\\u043d\\u043e, \\u0442\\u043e\\u0433\\u0434\\u0430 \\u0434\\u043e\\u0431\\u0430\\u0432\\u0438\\u0442\\u044c \\u0432 \\u0434\\u0430\\u043d\\u043d\\u043e\\u0435 \\u043f\\u043e\\u043b\\u0435"}',
                        'order' => 5,
                    ),
                    114 => 
                    array (
                        'id' => 197,
                        'data_type_id' => 22,
                        'field' => 'images',
                        'type' => 'multiple_images',
                        'display_name' => 'Галерея изображений',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"12"},"description":"\\u0415\\u0441\\u043b\\u0438 \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0439 \\u0431\\u0443\\u0434\\u0435\\u0442 \\u043c\\u043d\\u043e\\u0433\\u043e, \\u0442\\u043e\\u0433\\u0434\\u0430 \\u0434\\u043e\\u0431\\u0430\\u0432\\u0438\\u0442\\u044c \\u0432 \\u0434\\u0430\\u043d\\u043d\\u043e\\u0435 \\u043f\\u043e\\u043b\\u0435"}',
                        'order' => 6,
                    ),
                    115 => 
                    array (
                        'id' => 198,
                        'data_type_id' => 22,
                        'field' => 'price',
                        'type' => 'number',
                        'display_name' => 'Цена',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"description":"\\u0422\\u043e\\u043b\\u044c\\u043a\\u043e \\u0447\\u0438\\u0441\\u043b\\u043e\\u0432\\u043e\\u0435 \\u0437\\u043d\\u0430\\u0447\\u0435\\u043d\\u0438\\u0435, \\u043d\\u0430\\u043f\\u0440\\u0438\\u043c\\u0435\\u0440, 125,00"}',
                        'order' => 7,
                    ),
                    116 => 
                    array (
                        'id' => 199,
                        'data_type_id' => 22,
                        'field' => 'accessory_category_id',
                        'type' => 'text',
                        'display_name' => 'Категория',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 8,
                    ),
                    117 => 
                    array (
                        'id' => 200,
                        'data_type_id' => 22,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 9,
                    ),
                    118 => 
                    array (
                        'id' => 201,
                        'data_type_id' => 22,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 10,
                    ),
                    119 => 
                    array (
                        'id' => 202,
                        'data_type_id' => 23,
                        'field' => 'id',
                        'type' => 'number',
                        'display_name' => '№',
                        'required' => 1,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"1"}}',
                        'order' => 1,
                    ),
                    120 => 
                    array (
                        'id' => 203,
                        'data_type_id' => 23,
                        'field' => 'name',
                        'type' => 'text',
                        'display_name' => 'Наименование',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"}}',
                        'order' => 2,
                    ),
                    121 => 
                    array (
                        'id' => 204,
                        'data_type_id' => 23,
                        'field' => 'image',
                        'type' => 'image',
                        'display_name' => 'Изображение',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"2"},"description":"\\u041e\\u0441\\u043d\\u043e\\u0432\\u043d\\u043e\\u0435 \\u0438\\u0437\\u043e\\u0431\\u0440\\u0430\\u0436\\u0435\\u043d\\u0438\\u0435 \\u043a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0438\\u0438"}',
                        'order' => 3,
                    ),
                    122 => 
                    array (
                        'id' => 205,
                        'data_type_id' => 23,
                        'field' => 'created_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата создания',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 4,
                    ),
                    123 => 
                    array (
                        'id' => 206,
                        'data_type_id' => 23,
                        'field' => 'updated_at',
                        'type' => 'timestamp',
                        'display_name' => 'Дата обновления',
                        'required' => 0,
                        'browse' => 0,
                        'read' => 0,
                        'edit' => 0,
                        'add' => 0,
                        'delete' => 0,
                        'details' => '{"display":{"width":"2"}}',
                        'order' => 5,
                    ),
                    124 => 
                    array (
                        'id' => 207,
                        'data_type_id' => 22,
                        'field' => 'accessory_belongsto_accessory_category_relationship',
                        'type' => 'relationship',
                        'display_name' => 'Категория',
                        'required' => 0,
                        'browse' => 1,
                        'read' => 1,
                        'edit' => 1,
                        'add' => 1,
                        'delete' => 1,
                        'details' => '{"display":{"width":"4"},"model":"App\\\\Models\\\\AccessoryCategory","table":"accessory_categories","type":"belongsTo","column":"accessory_category_id","key":"id","label":"name","pivot_table":"accessories","pivot":"0","taggable":"0"}',
                        'order' => 3,
                    ),
                ));
       } catch(Exception $e) {
         throw new Exception('Exception occur ' . $e);

         \DB::rollBack();
       }

       \DB::commit();
    }
}
