<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Menu_itemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
     try {
        \DB::beginTransaction();

        \DB::table('menu_items')->delete();

        \DB::table('menu_items')->insert(array (
                0 => 
                array (
                    'id' => 1,
                    'menu_id' => 1,
                    'title' => 'Панель управления',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-boat',
                    'color' => NULL,
                    'parent_id' => NULL,
                    'order' => 4,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2022-01-17 20:47:16',
                    'route' => 'voyager.dashboard',
                    'parameters' => NULL,
                ),
                1 => 
                array (
                    'id' => 2,
                    'menu_id' => 1,
                    'title' => 'Медиа',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-images',
                    'color' => NULL,
                    'parent_id' => NULL,
                    'order' => 5,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2022-01-22 19:30:36',
                    'route' => 'voyager.media.index',
                    'parameters' => NULL,
                ),
                2 => 
                array (
                    'id' => 3,
                    'menu_id' => 1,
                    'title' => 'Пользователи',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-person',
                    'color' => NULL,
                    'parent_id' => 1,
                    'order' => 2,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2022-01-16 14:48:04',
                    'route' => 'voyager.users.index',
                    'parameters' => NULL,
                ),
                3 => 
                array (
                    'id' => 4,
                    'menu_id' => 1,
                    'title' => 'Роли',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-lock',
                    'color' => NULL,
                    'parent_id' => 1,
                    'order' => 1,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2022-01-16 14:47:59',
                    'route' => 'voyager.roles.index',
                    'parameters' => NULL,
                ),
                4 => 
                array (
                    'id' => 5,
                    'menu_id' => 1,
                    'title' => 'Инструменты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-tools',
                    'color' => NULL,
                    'parent_id' => NULL,
                    'order' => 6,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2022-01-22 19:30:36',
                    'route' => NULL,
                    'parameters' => NULL,
                ),
                5 => 
                array (
                    'id' => 6,
                    'menu_id' => 1,
                    'title' => 'Конструктор Меню',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-list',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 1,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2021-08-19 11:08:19',
                    'route' => 'voyager.menus.index',
                    'parameters' => NULL,
                ),
                6 => 
                array (
                    'id' => 7,
                    'menu_id' => 1,
                    'title' => 'База данных',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-data',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 2,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2021-08-19 11:08:19',
                    'route' => 'voyager.database.index',
                    'parameters' => NULL,
                ),
                7 => 
                array (
                    'id' => 8,
                    'menu_id' => 1,
                    'title' => 'Compass',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-compass',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 3,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2021-08-19 11:08:20',
                    'route' => 'voyager.compass.index',
                    'parameters' => NULL,
                ),
                8 => 
                array (
                    'id' => 9,
                    'menu_id' => 1,
                    'title' => 'BREAD',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-bread',
                    'color' => NULL,
                    'parent_id' => 5,
                    'order' => 4,
                    'created_at' => '2021-08-19 05:43:33',
                    'updated_at' => '2021-08-19 11:08:20',
                    'route' => 'voyager.bread.index',
                    'parameters' => NULL,
                ),
                9 => 
                array (
                    'id' => 10,
                    'menu_id' => 1,
                    'title' => 'Настройки',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-settings',
                    'color' => NULL,
                    'parent_id' => NULL,
                    'order' => 7,
                    'created_at' => '2021-08-19 05:43:34',
                    'updated_at' => '2022-01-22 19:30:37',
                    'route' => 'voyager.settings.index',
                    'parameters' => NULL,
                ),
                10 => 
                array (
                    'id' => 15,
                    'menu_id' => 1,
                    'title' => 'Категории',
                    'url' => '/admin/categories',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 1,
                    'created_at' => '2021-08-19 11:13:36',
                    'updated_at' => '2022-01-16 14:47:24',
                    'route' => NULL,
                    'parameters' => '',
                ),
                11 => 
                array (
                    'id' => 16,
                    'menu_id' => 1,
                    'title' => 'Материал',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 2,
                    'created_at' => '2021-08-19 12:47:31',
                    'updated_at' => '2022-01-16 14:50:17',
                    'route' => 'voyager.materials.index',
                    'parameters' => 'null',
                ),
                12 => 
                array (
                    'id' => 17,
                    'menu_id' => 1,
                    'title' => 'Цветники',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 5,
                    'created_at' => '2021-09-04 20:02:23',
                    'updated_at' => '2022-01-17 12:46:15',
                    'route' => 'voyager.parterres.index',
                    'parameters' => 'null',
                ),
                13 => 
                array (
                    'id' => 18,
                    'menu_id' => 1,
                    'title' => 'Стеллы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 3,
                    'created_at' => '2021-09-05 18:35:55',
                    'updated_at' => '2022-01-17 12:46:03',
                    'route' => 'voyager.stellas.index',
                    'parameters' => 'null',
                ),
                14 => 
                array (
                    'id' => 19,
                    'menu_id' => 1,
                    'title' => 'Услуги',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-tools',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 3,
                    'created_at' => '2021-09-06 19:05:17',
                    'updated_at' => '2022-01-22 19:32:48',
                    'route' => 'voyager.services.index',
                    'parameters' => 'null',
                ),
                15 => 
                array (
                    'id' => 21,
                    'menu_id' => 1,
                    'title' => 'Тумбы',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 4,
                    'created_at' => '2021-09-24 06:06:34',
                    'updated_at' => '2022-01-17 12:46:12',
                    'route' => 'voyager.pedestals.index',
                    'parameters' => 'null',
                ),
                16 => 
                array (
                    'id' => 22,
                    'menu_id' => 1,
                    'title' => 'Надгробные плиты',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 6,
                    'created_at' => '2021-09-24 07:26:54',
                    'updated_at' => '2022-01-17 12:46:17',
                    'route' => 'voyager.tombstones.index',
                    'parameters' => 'null',
                ),
                17 => 
                array (
                    'id' => 23,
                    'menu_id' => 1,
                    'title' => 'Столбики',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 7,
                    'created_at' => '2021-10-25 14:40:19',
                    'updated_at' => '2022-01-17 12:46:17',
                    'route' => 'voyager.pillars.index',
                    'parameters' => 'null',
                ),
                18 => 
                array (
                    'id' => 25,
                    'menu_id' => 1,
                    'title' => 'Католог памятников',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-list',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 1,
                    'created_at' => '2022-01-15 19:06:55',
                    'updated_at' => '2022-01-22 19:29:32',
                    'route' => NULL,
                    'parameters' => '',
                ),
                19 => 
                array (
                    'id' => 26,
                    'menu_id' => 2,
                    'title' => 'Памятники',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-list',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 1,
                    'created_at' => '2022-01-15 19:30:02',
                    'updated_at' => '2022-01-15 19:31:06',
                    'route' => NULL,
                    'parameters' => '',
                ),
                20 => 
                array (
                    'id' => 27,
                    'menu_id' => 2,
                    'title' => 'Категории',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 26,
                    'order' => 1,
                    'created_at' => '2022-01-15 19:31:03',
                    'updated_at' => '2022-01-15 19:31:06',
                    'route' => 'voyager.categories.index',
                    'parameters' => NULL,
                ),
                21 => 
                array (
                    'id' => 29,
                    'menu_id' => 1,
                    'title' => 'Памятники',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 25,
                    'order' => 8,
                    'created_at' => '2022-01-16 14:51:12',
                    'updated_at' => '2022-01-16 14:51:22',
                    'route' => 'voyager.products.index',
                    'parameters' => NULL,
                ),
                22 => 
                array (
                    'id' => 31,
                    'menu_id' => 1,
                    'title' => 'Каталог аксессуаров',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-trophy',
                    'color' => '#000000',
                    'parent_id' => NULL,
                    'order' => 2,
                    'created_at' => '2022-01-16 16:34:02',
                    'updated_at' => '2022-01-22 19:32:48',
                    'route' => NULL,
                    'parameters' => '',
                ),
                23 => 
                array (
                    'id' => 35,
                    'menu_id' => 1,
                    'title' => 'Аксессуары',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-list',
                    'color' => '#000000',
                    'parent_id' => 31,
                    'order' => 2,
                    'created_at' => '2022-01-17 20:46:50',
                    'updated_at' => '2022-01-22 19:31:52',
                    'route' => 'voyager.accessories.index',
                    'parameters' => 'null',
                ),
                24 => 
                array (
                    'id' => 36,
                    'menu_id' => 1,
                    'title' => 'Категории',
                    'url' => '',
                    'target' => '_self',
                    'icon_class' => 'voyager-categories',
                    'color' => '#000000',
                    'parent_id' => 31,
                    'order' => 1,
                    'created_at' => '2022-01-17 20:49:09',
                    'updated_at' => '2022-01-22 19:31:52',
                    'route' => 'voyager.accessory-categories.index',
                    'parameters' => 'null',
                ),
            ));
       } catch(Exception $e) {
         throw new Exception('Exception occur ' . $e);

         \DB::rollBack();
       }

       \DB::commit();
    }
}
